In [54]:
import numpy as np
np.set_printoptions(precision=5,suppress=True)

In [3]:
#first, we consider a system with three possible states, with equilibrium probability values:
p = np.array([0.2,0.3,0.5])

In [6]:
#let the transition rate matrix T_ij be:
T_ij = np.array(range(1,10),dtype=float).reshape(3,3)

In [7]:
T_ij

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [11]:
#Now, we form the matrix W, using the master equation
W = np.zeros((3,3))
for i in range(3):
    for j in range(3):
        if j==i:
            W[i,j] = -sum([T_ij[i,k] for k in range(3)])+T_ij[i,i]
        else:
            W[i,j] = T_ij[i,j]

In [12]:
W

array([[ -5.,   2.,   3.],
       [  4., -10.,   6.],
       [  7.,   8., -15.]])

In [16]:
S = np.diag(np.sqrt(p))
S_1 = np.diag(np.sqrt(1./p))

In [21]:
omega = np.dot(S,W).dot(S_1)

In [22]:
np.linalg.eig(omega)

(array([  0.        ,  -9.80384758, -20.19615242]),
 array([[-0.4472136 , -0.44990212, -0.07363334],
        [-0.54772256,  0.73637123, -0.38412744],
        [-0.70710678,  0.50531723,  0.9203392 ]]))

In [23]:
np.linalg.eig(W)

(array([ 3.55271368e-15, -9.80384758e+00, -2.01961524e+01]),
 array([[-0.57735027, -0.55127233, -0.1106798 ],
        [-0.57735027,  0.7367147 , -0.47143692],
        [-0.57735027,  0.39159962,  0.87492698]]))

In [29]:
#create example 4x4 transiton matrix.
#First,create the matrix
W=np.array(range(1,17),dtype=float).reshape(4,4)

In [30]:
# Now, disconnect 2x2 diagonal blocks
W[0:2,2:] = np.zeros((2,2))
W[2:,0:2] = np.zeros((2,2))
W

array([[ 1.,  2.,  0.,  0.],
       [ 5.,  6.,  0.,  0.],
       [ 0.,  0., 11., 12.],
       [ 0.,  0., 15., 16.]])

In [48]:
#Now, give W it's proper form
W_old=W.copy()
for i in range(4):
    for j in range(4):
        if j==i:
            W[i,j] = -sum([W_old[i,k] for k in range(4)])+W_old[i,i]
        else:
            W[i,j] = W_old[i,j]
W

array([[ -2.,   2.,   0.,   0.],
       [  5.,  -5.,   0.,   0.],
       [  0.,   0., -12.,  12.],
       [  0.,   0.,  15., -15.]])

In [55]:
r,vr = np.linalg.eig(W)
print(np.sort(r))

[-27.  -7.   0.   0.]
