In [7]:
import numpy as np
from scipy.special import factorial

In [8]:
Lmax=4
NYlm = (Lmax + 1) ** 2 #No. of spherical harmonics basis functions upto l=Lmax

Npower = NYlm + ((Lmax + 1) * Lmax * (Lmax - 1)) // 6 #no of terms in a homogeneous polynomial of order Lmax
pow2ind = -np.ones((Lmax + 1, Lmax + 1, Lmax + 1), dtype=int)
ind2pow = np.zeros((Npower, 3), dtype=int)
powlrange = np.zeros(Lmax + 2, dtype=int)
powlrange[-1] = 0
ind=0
for l in range(Lmax + 1):
    for n1 in range(l + 1):
        for n2 in range(l + 1 - n1):
            n3 = l - n1 - n2
            pow2ind[n1, n2, n3] = ind
            ind2pow[ind, 0], ind2pow[ind, 1], ind2pow[ind, 2] = n1, n2, n3
            ind += 1
    powlrange[l] = ind

In [9]:
powlrange
#powlrange[j] -> how many homogeneous polynomials upto order j
#example if j=3, how many homogeneous polynomial terms for l=0,1,2,3 -> see the GM notebook

array([ 1,  4, 10, 20, 35,  0])

In [10]:
ind2pow #-each row is the powers of the components of 'p' or 'q' for a certain order homogenous polynomial
        #made out of them

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 2],
       [0, 1, 1],
       [0, 2, 0],
       [1, 0, 1],
       [1, 1, 0],
       [2, 0, 0],
       [0, 0, 3],
       [0, 1, 2],
       [0, 2, 1],
       [0, 3, 0],
       [1, 0, 2],
       [1, 1, 1],
       [1, 2, 0],
       [2, 0, 1],
       [2, 1, 0],
       [3, 0, 0],
       [0, 0, 4],
       [0, 1, 3],
       [0, 2, 2],
       [0, 3, 1],
       [0, 4, 0],
       [1, 0, 3],
       [1, 1, 2],
       [1, 2, 1],
       [1, 3, 0],
       [2, 0, 2],
       [2, 1, 1],
       [2, 2, 0],
       [3, 0, 1],
       [3, 1, 0],
       [4, 0, 0]])

In [11]:
uniq_pow_terms=[]
uniq_pow_term_count=[]
for i in range(len(ind2pow)):
    s = sum(ind2pow[i])
    if not any(s1==s for s1 in uniq_pow_terms):
        uniq_pow_terms.append(s)
        uniq_pow_term_count.append(1)
    else:
        for idx,j in enumerate(uniq_pow_terms):
            if s==j:
                uniq_pow_term_count[idx] += 1

In [12]:
uniq_pow_terms

[0, 1, 2, 3, 4]

In [13]:
uniq_pow_term_count

[1, 3, 6, 10, 15]

In [14]:
lmax = 3
for l in range(lmax+1):
    for n1 in range(l+1):
        for n2 in range(l+1-n1):
            n3=l-n1-n2
            

In [15]:
pow2ind[1][0][0]

3

In [16]:
pow2ind

array([[[ 0,  1,  4, 10, 20],
        [ 2,  5, 11, 21, -1],
        [ 6, 12, 22, -1, -1],
        [13, 23, -1, -1, -1],
        [24, -1, -1, -1, -1]],

       [[ 3,  7, 14, 25, -1],
        [ 8, 15, 26, -1, -1],
        [16, 27, -1, -1, -1],
        [28, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1]],

       [[ 9, 17, 29, -1, -1],
        [18, 30, -1, -1, -1],
        [31, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1]],

       [[19, 32, -1, -1, -1],
        [33, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1]],

       [[34, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1]]])

In [17]:
ind=0
Ylm2ind = -np.ones((Lmax + 1, 2 * Lmax + 1), dtype=int)
ind2Ylm = np.zeros((NYlm, 2), dtype=int)
for l in range(Lmax + 1):
    for m in range(-l, l + 1):
        Ylm2ind[l, m] = ind
        ind2Ylm[ind, 0], ind2Ylm[ind, 1] = l, m
        ind += 1

In [18]:
Ylm2ind

array([[ 0, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 2,  3, -1, -1, -1, -1, -1, -1,  1],
       [ 6,  7,  8, -1, -1, -1, -1,  4,  5],
       [12, 13, 14, 15, -1, -1,  9, 10, 11],
       [20, 21, 22, 23, 24, 16, 17, 18, 19]])

In [19]:
ind2Ylm

array([[ 0,  0],
       [ 1, -1],
       [ 1,  0],
       [ 1,  1],
       [ 2, -2],
       [ 2, -1],
       [ 2,  0],
       [ 2,  1],
       [ 2,  2],
       [ 3, -3],
       [ 3, -2],
       [ 3, -1],
       [ 3,  0],
       [ 3,  1],
       [ 3,  2],
       [ 3,  3],
       [ 4, -4],
       [ 4, -3],
       [ 4, -2],
       [ 4, -1],
       [ 4,  0],
       [ 4,  1],
       [ 4,  2],
       [ 4,  3],
       [ 4,  4]])

In [20]:
Ylm2ind[1,-1]
#this means l=1,m=-1 is stored in index 1 of ind2Ylm

1

In [21]:
powlrange #-> these are the Npower quantities for a given Lmax

array([ 1,  4, 10, 20, 35,  0])

In [27]:
#powerexp -> the powercoeff list
powerexp = np.zeros((Lmax+1,Npower))

In [34]:
for n0 in range(Lmax+1):
    for n1 in range(Lmax+1):
        for n2 in range(Lmax+1):
            n=n1+n2+n3
            if n<=Lmax:
                powerexp[n][pow2ind[n0,n1,n2]] = factorial(n,True)/(factorial(n0,True)*factorial(n1,True)*factorial(n2,True))
                if(n==2):
                    print("n1,n2,n3 :{}, {}, {}".format(n0,n1,n2))
                    print("indexvalue in ind2pow : {}".format(pow2ind[n0,n1,n2]))
                    print()

n1,n2,n3 :0, 0, 2
indexvalue in ind2pow : 4

n1,n2,n3 :0, 1, 1
indexvalue in ind2pow : 5

n1,n2,n3 :0, 2, 0
indexvalue in ind2pow : 6

n1,n2,n3 :1, 0, 2
indexvalue in ind2pow : 14

n1,n2,n3 :1, 1, 1
indexvalue in ind2pow : 15

n1,n2,n3 :1, 2, 0
indexvalue in ind2pow : 16

n1,n2,n3 :2, 0, 2
indexvalue in ind2pow : 29

n1,n2,n3 :2, 1, 1
indexvalue in ind2pow : 30

n1,n2,n3 :2, 2, 0
indexvalue in ind2pow : 31

n1,n2,n3 :3, 0, 2
indexvalue in ind2pow : -1

n1,n2,n3 :3, 1, 1
indexvalue in ind2pow : -1

n1,n2,n3 :3, 2, 0
indexvalue in ind2pow : -1

n1,n2,n3 :4, 0, 2
indexvalue in ind2pow : -1

n1,n2,n3 :4, 1, 1
indexvalue in ind2pow : -1

n1,n2,n3 :4, 2, 0
indexvalue in ind2pow : -1



In [35]:
ind2pow

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 2],
       [0, 1, 1],
       [0, 2, 0],
       [1, 0, 1],
       [1, 1, 0],
       [2, 0, 0],
       [0, 0, 3],
       [0, 1, 2],
       [0, 2, 1],
       [0, 3, 0],
       [1, 0, 2],
       [1, 1, 1],
       [1, 2, 0],
       [2, 0, 1],
       [2, 1, 0],
       [3, 0, 0],
       [0, 0, 4],
       [0, 1, 3],
       [0, 2, 2],
       [0, 3, 1],
       [0, 4, 0],
       [1, 0, 3],
       [1, 1, 2],
       [1, 2, 1],
       [1, 3, 0],
       [2, 0, 2],
       [2, 1, 1],
       [2, 2, 0],
       [3, 0, 1],
       [3, 1, 0],
       [4, 0, 0]])

In [45]:
print(powerexp[3][10:14])
print(ind2pow[10:14])

[1. 3. 3. 1.]
[[0 0 3]
 [0 1 2]
 [0 2 1]
 [0 3 0]]


In [44]:
print(powerexp[2][4:7])

[1. 2. 1.]


In [ ]:
u = np.array([0.3,0.7,0.9])