In [1]:
import numpy as np

In [2]:
jngraph = np.zeros((3,3),dtype=bool)
jngraph

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [11]:
jngraph[0,1]=True
jngraph[1,0]=True
jngraph[0,2]=False
jngraph[2,0]=False
jngraph
#Work out what the connectivity should be?

array([[False,  True, False],
       [ True, False, False],
       [False, False, False]])

In [12]:
connectivity = 0
disconnected = {i for i in range(3)}#this is a set.
#If a certain site is found to be connected to some other site, it will be removed from this site.
#Note that in a real jumpnetwork, the diagonal elements of jngraph will be false, since we don't calculate those jumps.
print(disconnected)
while len(disconnected)>0:
    # take the "first" element out, and find everything it's connected to:
    i = min(disconnected)
    cset = {i}
    disconnected.remove(i)
    while True:
        clen = len(cset)
        for n in cset.copy():
            for m in disconnected.copy():
                if jngraph[n,m]:#Are the two sites connected by a jump?
                    cset.add(m)
                    disconnected.remove(m)
        # check if we've stopped adding new members:
        if clen == len(cset): break
    connectivity += 1
print(disconnected)

{0, 1, 2}
set()


In [13]:
connectivity

2

In [13]:
#Now make two and three absolutely disconnected, i.e, disconnect 1 from 3.
#So now, we will have 1-2 connected. 3 on it's own. So connectivity should be 2.
jngraph[0,2]=False
jngraph[2,0]=False
jngraph

array([[False,  True, False],
       [ True, False, False],
       [False, False, False]])

In [14]:
connectivity = 0
disconnected = {i for i in range(3)}#this is a set.
while len(disconnected)>0:
    # take the "first" element out, and find everything it's connected to:
    i = min(disconnected)
    cset = {i}
    disconnected.remove(i)
    while True:
        clen = len(cset)
        for n in cset.copy():
            for m in disconnected.copy():
                if jngraph[n,m]:
                    cset.add(m)
                    disconnected.remove(m)
        # check if we've stopped adding new members:
        if clen == len(cset): break
    connectivity += 1

In [15]:
connectivity

2

In [16]:
import onsager.crystal as crystal

In [17]:
FCC = crystal.Crystal.FCC(1.)

In [18]:
FCC

Crystal(array([[0. , 0.5, 0.5],       [0.5, 0. , 0.5],       [0.5, 0.5, 0. ]]),[[array([0., 0., 0.])]], spins=None, chemistry=['0'])